### PR TITLE
Fan page update

### PR DESCRIPTION
**Pull request by huskerman34**
Fixed the wrapper and updated the html and css style sheet

### CODE REVIEW

**Comment by huskerman34** [comment]
updated

**Comment by mbMosman** [comment]
You've got a lot of validation errors.  Make sure you are running your pages through the HTML & CSS validator.

**Comment by huskerman34** [comment]
Need someone to look this over. I think it's in the margins.

**Comment by huskerman34** [comment]
getting ready to fix error

**Comment by huskerman34** [comment]
fan page submission fixed errors!!!!

**Comment by mbMosman** [comment]
You've still got validation errors for your HTML.  There was no screenshot for validation of the HTML, only CSS and that showed an error.
https://html5.validator.nu/?doc=https%3A%2F%2Fhuskerman34.github.io%2Ffan-page%2F

**Pull request closed without merging**
